name: PHP 8.1

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Debian image
        uses: docker/build-push-action@v2
        with:
          context: build/debian
          target: base
          pull: true
          push: false
          tags: kovalevpw/openvpn:php-8.1
      -
        name: Push Debian image
        uses: docker/build-push-action@v2
        with:
          context: build/debian
          target: base
          pull: false
          push: true
          tags: kovalevpw/openvpn:php-8.1
        if: success() && github.ref == 'refs/heads/master'
